### ISSUE TITLE
size_policy is broken

### ISSUE THREAD

**Issue by rabernat** [martindurant/filesystem_spec#52]
In #46, @martindurant added a `size_policy` keyword to HTTPFileSystem.

In fsspec 0.2.1, it appears to be broken.
```python
from fsspec.implementations.http import HTTPFileSystem
fs = HTTPFileSystem()
path = 'https://data.nas.nasa.gov/ecco/download_data.php?file=/eccodata/llc_2160/compressed/0000092160/Theta.0000092160.data.shrunk'
f = fs.open(path, size_policy='get')
```
raises
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-15-857d04d27e7c> in <module>()
      2 fs = HTTPFileSystem()
      3 path = 'https://data.nas.nasa.gov/ecco/download_data.php?file=/eccodata/llc_2160/compressed/0000092160/Theta.0000092160.data.shrunk'
----> 4 f = fs.open(path, size_policy='get')

~/miniconda3/envs/geo_scipy/lib/python3.6/site-packages/fsspec/spec.py in open(self, path, mode, block_size, **kwargs)
    615             ac = kwargs.pop('autocommit', not self._intrans)
    616             f = self._open(path, mode=mode, block_size=block_size,
--> 617                            autocommit=ac, **kwargs)
    618             if not ac:
    619                 self.transaction.files.append(f)

~/miniconda3/envs/geo_scipy/lib/python3.6/site-packages/fsspec/implementations/http.py in _open(self, url, mode, block_size, **kwargs)
    131         if block_size:
    132             return HTTPFile(self, url, self.session, block_size,
--> 133                             size_policy=self.size_policy, **kw)
    134         else:
    135             kw['stream'] = True

TypeError: type object got multiple values for keyword argument 'size_policy'
```

**Comment by martindurant** [comment]
Ah, the intent was to do
```
fs = HTTPFileSystem(size_policy='get')
f = fs.open(path)
```
but both routes should have worked. Fix coming.

**Comment by martindurant** [comment]
Does this mean that you would like a 0.2.2?

**Comment by rabernat** [comment]
No I can work around!

**Comment by rabernat** [comment]
Perhaps I am being naive here, but isn't this why we have unit tests? I fear that fsspec is a bit light on testing. Is this intentional?

**Comment by martindurant** [comment]
Yes, fsspec is poorly tested. The code has been very much features-first here. There are decent tests for the local filesystem, but actually the best tests are in https://github.com/dask/s3fs/pull/161 . The implementations are tricky to test, and there's already a good deal of complexity here for the various external systems to be brought online, some of which (hadoop) are already flaky. The file-systems are not generally similar enough that I could easily write tests that can be run on all implementations.

Maybe it would be worthwhile splitting the tests into separate travis tasks for each implementation requiring docker work. Certainly would be worthwhile moving this repo to dask or intake, so that I can push to a fork and not have travis make two jobs for every commit.

Any tests you come up with during regular use of this library would be very much appreciated in the code. The case of HTTP is particularly tricky, since the standard python server only gives one particular set of behaviours, and we would either have to build a python server (tornado, etc.) to handle all the cases or call docker containers with various file servers.

Thoughts on how to make this package the thing it should be?

**Comment by rabernat** [comment]
Thanks for clarifying the difficulty related to testing. Yes I see how this is hard, because the implementations depend on outside services / APIs.

I guess my feeling is that perfect should not be the enemy of good. It should be possible to create simple fixtures to represent the different backends (http server, ftp server, etc.) and cover 90% of the functionality.
